services:

  postgres:
    image: postgres:16
    container_name: makeen_postgres

    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - main

    restart: always


  app:
    build: .

    container_name: makeen_app

    command: >
      sh -c "
      python manage.py migrate &&
      gunicorn Food.wsgi:application --bind 0.0.0.0:8000
      "

    env_file:
      - .env

    volumes:
      - .:/code
      - media_data:/code/media

    expose:
      - "8000"

    depends_on:
      - postgres

    networks:
      - main

    restart: always



  nginx:
    image: nginx:latest

    container_name: makeen_nginx

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - media_data:/code/media

    depends_on:
      - app

    networks:
      - main

    restart: always



networks:
  main:


volumes:
  postgres_data:

  media_data: