services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always

    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - main

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5


  app:
    build: .
    container_name: makeen_app
    restart: always

    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "

    volumes:
      - .:/code
      - media:/code/media

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - main


networks:
  main:


volumes:
  postgres_data:
  media: