# Generated by Django 6.0.7 on 2026-07-12 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_delete_package_delete_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumodel',
            name='price',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menumodel',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.food'),
        ),
    ]
